name: hellowcity
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_auth: 3.3.5
  firebase_core: 1.11.0
  http: 0.13.4
  image_picker: 0.8.4+4
  file_picker: 4.3.2
  connectivity: 3.0.6
  flutter_datetime_picker: 1.5.1
  image: 3.1.1
  path_provider: 2.0.8
  flutter_spinkit: 5.1.0
  permission_handler: 8.3.0
  shared_preferences: 2.0.12
  carousel_slider: 4.0.0
  flutter_rating_bar: 4.0.0
  flutter_swiper_null_safety: 1.0.2
  cached_network_image: 3.2.0
  location: 4.3.0
  animated_text_kit: 4.2.1
  percent_indicator: 4.0.0
  flutter_keyboard_visibility: 5.1.1
  flutter_barcode_scanner: 2.0.0
  firebase_messaging: 11.2.6
  flutter_local_notifications: 9.2.0
  cashfree_pg: 2.0.6+26
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: ic_launcher
  image_path: assets/round_logo.jpg
  ios: true

flutter: 
  assets: 
    - assets/
    - assets/image/
  fonts: 
    - family: LootdaIcons
      fonts: 
        - asset: assets/fonts/LootdaIcons.ttf
    - family: HellowcityIcons
      fonts: 
        - asset: assets/fonts/HellowcityIcons.ttf
    - family: AppMaterialIcons
      fonts: 
        - asset: assets/fonts/AppMaterialIcons.ttf
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
    - family: Rajdhani
      fonts: 
        - asset: assets/fonts/Rajdhani/Rajdhani-Light.ttf
        - asset: assets/fonts/Rajdhani/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani/Rajdhani-SemiBold.ttf
        - asset: assets/fonts/Rajdhani/Rajdhani-Bold.ttf
  uses-material-design: true

